# Generated by Django 3.2.4 on 2021-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('furigana', models.CharField(default='', max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('birthplace', models.CharField(default='', max_length=30)),
                ('hobby', models.CharField(default='', max_length=30)),
                ('company', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
