# Generated by Django 3.2.4 on 2021-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendslist', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='birthplace',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='furigana',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='hobby',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
