# Generated by Django 3.2.4 on 2021-06-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendslist', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='friendslist.category'),
        ),
    ]
